# Generated by Django 4.2.3 on 2023-07-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_employee_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.municipal'),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Qada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.province')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.province'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.qada'),
        ),
        migrations.AddField(
            model_name='municipal',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.province'),
        ),
        migrations.AddField(
            model_name='municipal',
            name='qada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.qada'),
        ),
    ]
