# Generated by Django 4.2.3 on 2023-07-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_province_alter_employee_municipal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipal',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipal',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.province'),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='qada',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.qada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qada',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qada',
            name='province',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.province'),
            preserve_default=False,
        ),
    ]
